services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env  # This loads environment variables from .env file
    environment:
      # Override or add specific environment variables here
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - scraper-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    container_name: scraper-api

networks:
  scraper-net:
    driver: bridge

volumes:
  logs:
  data: