version: '3.8'

services:
  unified-scraper-api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - REQUIRE_API_KEY=true
      - DEFAULT_API_KEY=${DEFAULT_API_KEY}
      - REQUEST_TIMEOUT=30
      - MAX_REQUESTS_PER_MINUTE=60
      - ALLOWED_ORIGINS=*
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - scraper-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - unified-scraper-api
    restart: unless-stopped
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge

volumes:
  data:
  logs: